name: CustomContexts
version: '${project.version}'
main: com.greenjon902.customcontexts.CustomContexts
api-version: 1.18
load: STARTUP
depend: [ LuckPerms ]
authors: [ GreenJon902 ]
description: Adding customisable contexts to luckperms
website: https://github.com/GreenJon902

commands:
  customcontexts:
    description: Manage custom contexts
    aliases: [cc, contexts]
    permission: customcontexts

permissions:
  customcontexts:
    default: op
    children:
      customcontexts.add: True
      customcontexts.remove: True
  add:
    default: op
  remove:
    default: op